#
# spec file for package epgnotify
#
# Copyright (c) 2013 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.



Name:           epgnotify
Version:        0
Release:        0.1
Summary:        Mail notification about appearing keywords in EPG data
License:        GPL-3.0+
Group:	        Productivity/Multimedia/Other
Source1:        epgnotify.php
Source2:        README.md
Url:            https://github.com/Aikhjarto/epgnotify
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
BuildArch:      noarch
Requires:       php
Recommends:     vdr
Recommends:     vdradmin-am, cron

%description 
This small script will search your local EPG data (generated by vdr) for interesting key words. If a keyword is found, epgnotify will send you a notification by mail. If vdradmin-am is available it will send you a link to directly record interesting programs.

%prep
# The prep section should be there even if it's empty.

%pre
# The pre section should be there even if it's emtpy.

%build
# The build section should be there even if it's empty.

%install
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_docdir}/%{name}
install -c -m 755 %{S:1} %{buildroot}%{_bindir}/epgnotify.php
install -c -m 644 %{S:2} %{buildroot}%{_docdir}/%{name}/README.md

mkdir -p %{buildroot}%{_sysconfdir}/cron.daily/
ln -sf /usr/bin/epgnotify.php %{buildroot}%{_sysconfdir}/cron.daily/epgnotify.php

%files
%defattr(-,root,root,-)
%{_bindir}/epgnotify.php
%doc %{_docdir}/%{name}/README.md
%dir %{_docdir}/%{name}
%{_sysconfdir}/cron.daily/epgnotify.php

%changelog
* Fri Nov 29 2013 Wagner Thomas <wagner-thomas@gmx.at> - 0-0.2
- Created RPM for the first time

