#
# spec file for package epgnotify
#
# Copyright (c) 2013 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.



Name:           epgnotify
Version:        0
Release:        0.1
Summary:        Mail notification about appearing keywords in EPG data
License:        GPL-3.0+
Source1:        epgnotify.php
Source2:        README.md
Source3:        epgnotify.ini
Url:            https://github.com/Aikhjarto/epgnotify
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
BuildArch:      noarch
Requires:       php
Recommends:     vdr
Recommends:     vdradmin-am

%description 
This small script will search your local EPG data (generated by vdr) for interesting key words. If a keyword is found, epgnotify will send you a notification by mail. If vdradmin-am is available it will send you a link to directly record interesting programs.

%pre

%build
echo 1

%install
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_docdir}/%{name}
mkdir -p %{buildroot}/root
cp %{S:1} %{buildroot}%{_bindir}/epgnotify.php
cp %{S:2} %{buildroot}%{_docdir}/%{name}/README.md
cp %{S:3} %{buildroot}/root/.epgnotify.ini

mkdir -p %{buildroot}%{_sysconfdir}/cron.daily/
ln -sf /usr/bin/epgnotify.php %{buildroot}%{_sysconfdir}/cron.daily/epgnotify.php

%files
%defattr(-,root,root,-)
%{_bindir}/epgnotify.php
/root/.epgnotify.ini
%doc %{_docdir}/%{name}/README.md
%{_sysconfdir}/cron.daily/epgnotify.php

%changelog
